### ISSUE TITLE
Looping over object and making them promises `handler.apply is not a function`

### ISSUE THREAD

**Issue by reggi** [alex-whitney/express-promise-router#15]
I'm performing a lot of tests on individual pieces of middleware. There's a complication when testing promised middleware that if you have a function like the following:

```javascript
function(req, res){
  if(!req.query.hello) throw new Error("no hello query")
  return Promise.resolve("next")
}
```

You have a function that returns a promise some of the time and throws an error some of the time. To make matters worse if I return an actual promise that throws an error too it gets even more complicated

```javascript
function(req, res){
  if(!req.query.hello) throw new Error("no hello query")
  return request("http://google.com")
    .then(function(){
      return "next"
    })
}
```

If this request fails I'll have an error in my `.catch` call, however if `req.query.hello` doesn't exist I have a normal thrown error.

My gut reaction is to wrap every call in a promise to ensure that we're always returning a promise.

```javascript
function(req, res){
  return Promise.resolve().then(function(){
    if(!req.query.hello) throw new Error("no hello query")
    return request("http://google.com").then(function(){
      return "next"
    })
  })
}
```

I was hoping for a better way. Since my middleware is one big object I was hoping to wrap each function in a promise programatically.

So I created these two wrapping functions.

```javascript
function makePromises(obj){
  return _.mapObject(obj, function(fn){
    return function(){
      var args = _.values(arguments)
      return Promise.resolve().then(function(){
        return fn.apply(null, args)
      })
    }
  })
}

makePromises({
  myMiddleware: function(req, res){
    if(!req.query.hello) throw new Error("no hello query")
    return request("http://google.com").then(function(){
      return "next"
    })
  }
})

function makeNestedPromises(obj){
  return _.mapObject(obj, function(fn){
    return function(){
      var args = _.values(arguments)
      var value = fn.apply(null, args)
      return function(){
        var args = _.values(arguments)
        return Promise.resolve().then(function(){
          return value.apply(null, args)
        })
      }
    }
  })
}

makeNestedPromises({
  myMiddleware: function(something){
    function(req, res){
      if(!req.query.hello) throw new Error("no hello query")
      return request(something).then(function(){
        return "next"
      })
    }  
  }
})
```

This worked great until I just got this error:

```
TypeError: handler.apply is not a function
    at handleReturn (/Users/thomas/Desktop/node-project-app/node-project/node_modules/express-promise-router/lib/express-promise-router.js:27:27)
    at /Users/thomas/Desktop/node-project-app/node-project/node_modules/express-promise-router/lib/express-promise-router.js:55:9
    at Layer.handle [as handle_request] (/Users/thomas/Desktop/node-project-app/node-project/node_modules/express/lib/router/layer.js:82:5)
    at next (/Users/thomas/Desktop/node-project-app/node-project/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/Users/thomas/Desktop/node-project-app/node-project/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/Users/thomas/Desktop/node-project-app/node-project/node_modules/express/lib/router/layer.js:82:5)
    at /Users/thomas/Desktop/node-project-app/node-project/node_modules/express/lib/router/index.js:267:22
    at Function.proto.process_params (/Users/thomas/Desktop/node-project-app/node-project/node_modules/express/lib/router/index.js:321:12)
    at next (/Users/thomas/Desktop/node-project-app/node-project/node_modules/express/lib/router/index.js:261:10)
    at next (/Users/thomas/Desktop/node-project-app/node-project/node_modules/express/lib/router/route.js:95:14)
    at /Users/thomas/Desktop/node-project-app/node-project/node_modules/express-promise-router/lib/express-promise-router.js:38:21
    at tryCatcher (/Users/thomas/Desktop/node-project-app/node-project/node_modules/express-promise-router/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/thomas/Desktop/node-project-app/node-project/node_modules/express-promise-router/node_modules/bluebird/js/main/promise.js:489:31)
    at Promise._settlePromiseAt (/Users/thomas/Desktop/node-project-app/node-project/node_modules/express-promise-router/node_modules/bluebird/js/main/promise.js:565:18)
    at Promise._settlePromises (/Users/thomas/Desktop/node-project-app/node-project/node_modules/express-promise-router/node_modules/bluebird/js/main/promise.js:681:14)
    at Async._drainQueue (/Users/thomas/Desktop/node-project-app/node-project/node_modules/express-promise-router/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/thomas/Desktop/node-project-app/node-project/node_modules/express-promise-router/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/thomas/Desktop/node-project-app/node-project/node_modules/express-promise-router/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:371:17)
```

I'd really appreciate any help you can provide! Thanks!

**Comment by reggi** [comment]
Hmm. I'm not exactly sure what the cause of that error is yet. I don't think it's as described above. I think I might not have a problem at all.

**Comment by alex-whitney** [comment]
Here's a quick test you can copy+paste into `express-promise-router.test.js` -- this passes for me.

```js
    it('should handle throws when returning a promise', function () {
        var err = new Error();
        router.get('/foo', function () {
            throw err;
            return Promise.resolve('next'); // jshint ignore:line
        });

        return bootstrap(router).then(function () {
            return GET('/foo');
        }).then(function () {
            assert.fail();
        }, function (error) {
            if (error.name !== 'AssertionError' && error.message !== 'expected 500 to equal 200') {
                assert.fail();
            }
        });
    });
```

Testing route handlers is always a bit of a challenge. The `res` object is very stateful, so you have to do a lot of work in order to correctly mock it out. Tests can be very fragile, as minor changes to your handler can require you to update your tests. Furthermore, this module increases the functionality that your tests would also need to account for. 

It's a lot easier to just fire up a server, mount your express app, and hit your endpoints. Or depending on what you are doing, [supertest](https://github.com/visionmedia/supertest) may fit your needs well and reduce a lot of that overhead.

**Comment by reggi** [comment]
Thanks!
