### ISSUE TITLE
router.param broken entirely

### ISSUE THREAD

**Issue by joepie91** [alex-whitney/express-promise-router#21]
When using `router.param`, an unexpected error will occur if the returned Promise ends up rejecting:

```
sven@linux-etoq:~/projects/express-promise-router-bugcase> node index.js 
Incoming request: GET /item/42
Got itemId
/home/sven/projects/express-promise-router-bugcase/node_modules/express-promise-router/node_modules/bluebird/js/main/promise.js:677
            throw e;
            ^

TypeError: next is not a function
    at /home/sven/projects/express-promise-router-bugcase/node_modules/express-promise-router/lib/express-promise-router.js:44:17
    at tryCatcher (/home/sven/projects/express-promise-router-bugcase/node_modules/express-promise-router/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/sven/projects/express-promise-router-bugcase/node_modules/express-promise-router/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/home/sven/projects/express-promise-router-bugcase/node_modules/express-promise-router/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/home/sven/projects/express-promise-router-bugcase/node_modules/express-promise-router/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/home/sven/projects/express-promise-router-bugcase/node_modules/express-promise-router/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/sven/projects/express-promise-router-bugcase/node_modules/express-promise-router/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/sven/projects/express-promise-router-bugcase/node_modules/express-promise-router/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:368:17)
```

The culprit is line 26 of express-promise-router:

```javascript
var next = args.slice(-1)[0];
```

... which incorrectly assumes the last function argument to be the `next` function, which is not the case for a `.param` callback (where the last argument is the parameter value, [per the Express docs](http://expressjs.com/en/4x/api.html#router.param)):

```javascript
router.param('user', function(req, res, next, id) {
    // ...
});
```

I've created a repository with a testcase; it can be found [here](https://github.com/joepie91/express-promise-router-bugcase).

**Comment by alex-whitney** [comment]
This should be fixed in 1.1.0
