### ISSUE TITLE
The race is not to the swift

### ISSUE THREAD

**Issue by whittle** [alex-whitney/express-promise-router#8]
When running `npm test`, I get all checks with the following exception inserted (paths edited to be relative for brevity and clarity): 

```
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
    at ServerResponse.header (./node_modules/express/lib/response.js:700:10)
    at ServerResponse.send (./node_modules/express/lib/response.js:154:12)
    at errHandler (./test/express-promise-router.test.js:277:17)
    at handleReturn (./lib/express-promise-router.js:27:27)
    at ./lib/express-promise-router.js:50:13
    at Layer.handle_error (./node_modules/express/lib/router/layer.js:58:5)
    at next (./node_modules/express/lib/router/route.js:108:13)
    at ./lib/express-promise-router.js:44:17
    at tryCatcher (./node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (./node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (./node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (./node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (./node_modules/bluebird/js/main/async.js:79:16)
    at Async._drainQueues ./node_modules/bluebird/js/main/async.js:89:10)
    at Immediate.Async.drainQueues [as _onImmediate] (./node_modules/bluebird/js/main/async.js:14:14)
```

It seems that the test “calls next if next is called even if the handler returns a promise” is executing the rejection in the promise returned by the first handler, which leads me to believe that the successful result of the test is incorrect. 

I have the following versions installed: 

```
$ npm ls --depth=0
express-promise-router@0.0.7 /Users/jason/Code/express-promise-router
├── bluebird@2.9.12
├── chai@1.10.0
├── express@4.12.0
├── grunt@0.4.5
├── grunt-contrib-jshint@0.7.2
├── grunt-mocha-test@0.10.2
├── jshint-stylish@0.1.5
├── load-grunt-tasks@0.2.1
├── lodash@2.4.1
├── methods@1.1.1
├── request@2.53.0
├── sinon@1.12.2
└── time-grunt@0.2.10
```

**Comment by alex-whitney** [comment]
The test result was successful -- but the problem is that `next` is being invoked twice. The first time is when it is directly invoked, and the second is when it is invoked when the returned promise is resolved. Technically, there's no reason why you _can't_ call `next` twice. In this case, it resulted in an error is because both calls tried to use `res.send`.

Thanks for pointing this out.
